- name: "manage worker1 and 2"
  hosts: all
  become: true
  tasks:
  - name: "ensure majed user exists"
    user:
      name: majed
      state: present
  - name: "ensure Alex user exists"
    user:
      name: alex
      state: absent
      
